version: "3.8"

services:
  db:
    container_name: db_patrimonix
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - rede_patrimonix
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}

  backend:
    container_name: backend_patrimonix
    build: ./Backend/
    restart: always
    volumes:
      - ./Backend/src:/app/src
      - ./Backend/prisma:/app/prisma
    networks:
      - rede_patrimonix
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEFAULT_LANG=${DEFAULT_LANG}
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
    depends_on:
      - db
    command: >
      sh -c "npx prisma generate && npm run deploy && npm run populate && npm start"

  frontend:
    container_name: frontend_patrimonix
    build: ./frontend/
    restart: always
    volumes:
      - ./frontend/src:/app/src
    networks:
      - rede_patrimonix
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - db
      - backend

networks:
  rede_patrimonix:
    driver: bridge

volumes:
  mysql_data:
